-- MySQL Script generated by MySQL Workbench
-- Fri Dec  7 11:29:23 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hr
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hr` ;

-- -----------------------------------------------------
-- Schema hr
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hr` DEFAULT CHARACTER SET utf8 ;
USE `hr` ;

-- -----------------------------------------------------
-- Table `hr`.`regions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hr`.`regions` ;

CREATE TABLE IF NOT EXISTS `hr`.`regions` (
  `region_id` INT NOT NULL AUTO_INCREMENT,
  `region_name` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`region_id`),
  UNIQUE INDEX `region_id_UNIQUE` (`region_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hr`.`countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hr`.`countries` ;

CREATE TABLE IF NOT EXISTS `hr`.`countries` (
  `country_id` CHAR(2) NOT NULL,
  `country_name` VARCHAR(40) NOT NULL,
  `region_id` INT NOT NULL,
  PRIMARY KEY (`country_id`),
  UNIQUE INDEX `country_id_UNIQUE` (`country_id` ASC) ,
  INDEX `fk_countries_regions_idx` (`region_id` ASC) ,
  CONSTRAINT `fk_countries_regions`
    FOREIGN KEY (`region_id`)
    REFERENCES `hr`.`regions` (`region_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hr`.`locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hr`.`locations` ;

CREATE TABLE IF NOT EXISTS `hr`.`locations` (
  `location_id` INT NOT NULL AUTO_INCREMENT,
  `street_address` VARCHAR(25) NOT NULL,
  `postal_code` VARCHAR(12) NOT NULL,
  `city` VARCHAR(30) NOT NULL,
  `state_province` VARCHAR(12) NOT NULL,
  `country_id` CHAR(2) NOT NULL,
  PRIMARY KEY (`location_id`),
  UNIQUE INDEX `location_id_UNIQUE` (`location_id` ASC) ,
  INDEX `fk_locations_countries1_idx` (`country_id` ASC) ,
  CONSTRAINT `fk_locations_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `hr`.`countries` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hr`.`departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hr`.`departments` ;

CREATE TABLE IF NOT EXISTS `hr`.`departments` (
  `department_id` INT NOT NULL AUTO_INCREMENT,
  `department_name` VARCHAR(30) NOT NULL,
  `location_id` INT NOT NULL,
  `manager_id` INT NOT NULL,
  PRIMARY KEY (`department_id`),
  UNIQUE INDEX `department_id_UNIQUE` (`department_id` ASC) ,
  INDEX `fk_departments_locations1_idx` (`location_id` ASC) ,
  CONSTRAINT `fk_departments_locations1`
    FOREIGN KEY (`location_id`)
    REFERENCES `hr`.`locations` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hr`.`jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hr`.`jobs` ;

CREATE TABLE IF NOT EXISTS `hr`.`jobs` (
  `job_id` VARCHAR(10) NOT NULL,
  `job_title` VARCHAR(45) NOT NULL,
  `min_salary` DECIMAL(10,2) NOT NULL,
  `max_salary` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`job_id`),
  UNIQUE INDEX `job_id_UNIQUE` (`job_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hr`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hr`.`employees` ;

CREATE TABLE IF NOT EXISTS `hr`.`employees` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `commission_pct` INT NOT NULL,
  `department_id` INT NOT NULL,
  `job_id` VARCHAR(10) NOT NULL,
  `salary` DECIMAL(10,2) NOT NULL,
  `manager_id` INT NOT NULL,
  `hire_date` DATE NOT NULL,
  PRIMARY KEY (`employee_id`),
  UNIQUE INDEX `employee_id_UNIQUE` (`employee_id` ASC) ,
  INDEX `fk_employees_departments1_idx` (`department_id` ASC) ,
  INDEX `fk_employees_jobs1_idx` (`job_id` ASC) ,
  CONSTRAINT `fk_employees_departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `hr`.`departments` (`department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_jobs1`
    FOREIGN KEY (`job_id`)
    REFERENCES `hr`.`jobs` (`job_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hr`.`job_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hr`.`job_history` ;

CREATE TABLE IF NOT EXISTS `hr`.`job_history` (
  `employee_id` INT NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `job_id` VARCHAR(10) NOT NULL,
  `department_id` INT NOT NULL,
  PRIMARY KEY (`start_date`, `employee_id`),
  INDEX `fk_job_history_jobs1_idx` (`job_id` ASC) ,
  INDEX `fk_job_history_departments1_idx` (`department_id` ASC) ,
  INDEX `fk_job_history_employees1_idx` (`employee_id` ASC) ,
  CONSTRAINT `fk_job_history_jobs1`
    FOREIGN KEY (`job_id`)
    REFERENCES `hr`.`jobs` (`job_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_history_departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `hr`.`departments` (`department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_history_employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `hr`.`employees` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hr`.`job_grades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hr`.`job_grades` ;

CREATE TABLE IF NOT EXISTS `hr`.`job_grades` (
  `grade_level` VARCHAR(2) NOT NULL,
  `lowest_sal` INT NOT NULL,
  `highest_sal` INT NOT NULL,
  PRIMARY KEY (`grade_level`),
  UNIQUE INDEX `grade_UNIQUE` (`grade_level` ASC) )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
